export function getCharacters () {
  return [
    { name: 'commander luke skywalker', alts: ['cls'] },
    { name: 'rey (jedi training)', alts: ['rjt'] },
    { name: 'asajj ventress', alts: [] },
    { name: 'bb-8', alts: ['bb8'] },
    { name: 'darth nihilus', alts: ['dn'] },
    { name: 'darth traya', alts: [] },
    { name: 'darth vader', alts: [] },
    { name: 'emperor palpatine', alts: ['ep', 'palp'] },
    { name: 'grand admiral thrawn', alts: [] },
    { name: 'grand master yoda', alts: ['gmy', 'gm yoda'] },
    { name: 'grand moff tarkin', alts: [] },
    { name: 'hermit yoda', alts: [] },
    { name: 'jyn erso', alts: [] },
    { name: 'kylo ren (unmasked)', alts: ['kru'] },
    { name: 'mother talzin', alts: [] },
    { name: 'obi-wan kenobi (old ben)', alts: ['obi wan', 'og ben'] },
    { name: 'r2-d2', alts: ['r2d2'] },
    { name: 'wampa', alts: [] },
    { name: 'bossk', alts: [] },
    { name: 'luke skywalker (farmboy)', alts: [] },
    { name: 'boba fett', alts: [] },
    { name: 'darth sion', alts: [] },
    { name: 'director krennic', alts: ['dk'] },
    { name: 'ahsoka tano (fulcrum)', alts: [] },
    { name: 'amilyn holdo', alts: [] },
    { name: 'barriss offee', alts: [] },
    { name: 'bodhi rook', alts: [] },
    { name: 'captain han solo', alts: ['chs'] },
    { name: 'captain phasma', alts: [] },
    { name: 'cassian andor', alts: [] },
    { name: 'cc-2224 "cody"', alts: [] },
    { name: 'chief chirpa', alts: [] },
    { name: 'clone wars chewbacca', alts: [] },
    { name: 'colonel starck', alts: [] },
    { name: 'count dooku', alts: [] },
    { name: 'ct-5555 "fives"', alts: [] },
    { name: 'darth maul', alts: [] },
    { name: 'darth sidious', alts: [] },
    { name: 'death trooper', alts: ['dt'] },
    { name: 'ezra bridger', alts: [] },
    { name: 'finn', alts: [] },
    { name: 'gar saxon', alts: [] },
    { name: 'garazeb "zeb" orrelios', alts: [] },
    { name: 'general veers', alts: ['gv'] },
    { name: 'han solo', alts: ['raid han'] },
    { name: 'hera syndulla', alts: [] },
    { name: 'imperial probe droid', alts: ['ipd'] },
    { name: 'k-2so', alts: ['k2', 'k2so'] },
    { name: 'kanan jarrus', alts: [] },
    { name: 'kylo ren', alts: [] },
    { name: 'logray', alts: [] },
    { name: 'luminara unduli', alts: [] },
    { name: 'nightsister initiate', alts: [] },
    { name: 'old daka', alts: [] },
    { name: 'pao', alts: [] },
    { name: 'paploo', alts: [] },
    { name: 'princess leia', alts: [] },
    { name: 'qui-gon jinn', alts: ['qgj'] },
    { name: 'rebel officer leia organa', alts: ['rolo'] },
    { name: 'rey (scavenger)', alts: [] },
    { name: 'rose tico', alts: [] },
    { name: 'sabine wren', alts: [] },
    { name: 'savage opress', alts: [] },
    { name: 'veteran smuggler chewbacca', alts: [] },
    { name: 'veteran smuggler han solo', alts: [] },
    { name: 'visas marr', alts: [] },
    { name: 'wicket', alts: [] },
    { name: 'stormtrooper han', alts: ['sth'] },
    { name: 'first order stormtrooper', alts: ['fost'] },
    { name: 'first order tie pilot', alts: ['fotp'] },
    { name: 'stormtrooper', alts: ['st'] },
    { name: 'baze malbus', alts: [] },
    { name: 'chirrut îmwe', alts: ['chirrut imwe'] },
    { name: 'general grievous', alts: [] },
    { name: 'general kenobi', alts: ['gk'] },
    { name: 'chopper', alts: [] },
    { name: 'teebo', alts: [] },
    { name: 'aayla secura', alts: [] },
    { name: 'admiral ackbar', alts: [] },
    { name: 'ahsoka tano', alts: [] },
    { name: 'bistan', alts: [] },
    { name: 'cad bane', alts: [] },
    { name: 'chief nebit', alts: [] },
    { name: 'ct-21-0408 "echo"', alts: [] },
    { name: 'ct-7567 "rex"', alts: [] },
    { name: 'dathcha', alts: [] },
    { name: 'dengar', alts: [] },
    { name: 'eeth koth', alts: [] },
    { name: 'greedo', alts: [] },
    { name: 'hk-47', alts: ['hk47'] },
    { name: 'ig-88', alts: ['ig88'] },
    { name: 'ima-gun di', alts: ['igd'] },
    { name: 'jawa engineer', alts: [] },
    { name: 'jawa scavenger', alts: [] },
    { name: 'jedi knight anakin', alts: ['jka'] },
    { name: 'kit fisto', alts: [] },
    { name: 'lobot', alts: [] },
    { name: 'mace windu', alts: [] },
    { name: 'nute gunray', alts: [] },
    { name: 'plo koon', alts: [] },
    { name: 'poe dameron', alts: [] },
    { name: 'poggle the lesser', alts: [] },
    { name: 'sun fac', alts: [] },
    { name: 'talia', alts: [] },
    { name: 'urorrur\'r\'r', alts: [] },
    { name: 'wedge antilles', alts: [] },
    { name: 'zam wesell', alts: [] },
    { name: 'lando calrissian', alts: [] },
    { name: 'b2 super battle droid', alts: [] },
    { name: 'biggs darklighter', alts: [] },
    { name: 'clone sergeant - phase i', alts: [] },
    { name: 'coruscant underworld police', alts: ['cup'] },
    { name: 'ewok elder', alts: ['ee'] },
    { name: 'ewok scout', alts: [] },
    { name: 'first order executioner', alts: ['fox'] },
    { name: 'first order officer', alts: ['foo'] },
    { name: 'first order sf tie pilot', alts: ['fosftp'] },
    { name: 'gamorrean guard', alts: [] },
    { name: 'geonosian soldier', alts: [] },
    { name: 'geonosian spy', alts: [] },
    { name: 'hoth rebel scout', alts: [] },
    { name: 'hoth rebel soldier', alts: [] },
    { name: 'ig-100 magnaguard', alts: ['ig100'] },
    { name: 'ig-86 sentinel droid', alts: ['ig86'] },
    { name: 'imperial super commando', alts: ['isc'] },
    { name: 'jawa', alts: [] },
    { name: 'jedi consular', alts: [] },
    { name: 'jedi knight guardian', alts: [] },
    { name: 'magmatrooper', alts: [] },
    { name: 'mob enforcer', alts: [] },
    { name: 'nightsister acolyte', alts: [] },
    { name: 'nightsister spirit', alts: [] },
    { name: 'nightsister zombie', alts: [] },
    { name: 'royal guard', alts: ['rg'] },
    { name: 'scarif rebel pathfinder', alts: [] },
    { name: 'shoretrooper', alts: ['sht'] },
    { name: 'sith assassin', alts: ['sa'] },
    { name: 'sith marauder', alts: [] },
    { name: 'sith trooper', alts: [] },
    { name: 'snowtrooper', alts: [] },
    { name: 'tie fighter pilot', alts: ['tfp'] },
    { name: 'tusken raider', alts: [] },
    { name: 'tusken shaman', alts: [] },
    { name: 'resistance pilot', alts: ['rp'] },
    { name: 'resistance trooper', alts: ['rt'] },
    { name: 'ugnaught', alts: [] }
  ]
}
